name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull from master
        run: git pull origin master

      - name: Install Dependencies and Build Laravel
        run: |
          composer install --ignore-platform-reqs
          php artisan optimize

      # - name: Build Next.js
      #   run: |
      #     cd resources/js
      #     npm install
      #     npm run build

      - name: Deploy to VPS
        env:
          PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.PROJECT_DIRECTORY }} && git pull origin master && composer install && php artisan migrate && cd resources/js && npm i && npm run build"
