name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull from master
        run: git pull origin master

      - name: Install Dependencies and Build Laravel
        run: |
          composer install
          php artisan optimize

      - name: Build Next.js
        run: |
          cd resources/js
          npm install
          npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
            ssh -i ${{ secrets.VPS_SSH_KEY }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd ${{ secrets.PROJECT_DIRECTORY }} && \
            sudo rm -rf * && \
            cp -R /github/workspace/cursus-meester/* ${{ secrets.PROJECT_DIRECTORY }} && \
            cp -R /github/workspace/resources/js/build/* ${{ secrets.PROJECT_DIRECTORY }}resources/js/_next/"
